// <auto-generated />
namespace Secure1API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VirtualUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VirtualUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201807030535571_VirtualUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
